### ISSUE TITLE
Small mistakes

### ISSUE THREAD

**Issue by LUOrenjia** [linaro-swg/hello_world#1]
**export TA_CROSS_COMPILE=$PWD/../toolchains/aarch64/bin/aarch64-linux-gnu** 
should be：
**export TA_CROSS_COMPILE=$PWD/../toolchains/aarch64/bin/aarch64-linux-gnu-**

missing '-' in the end

**Comment by vchong** [comment]
@LUOrenjia Thanks! This has been fixed. :)
