### ISSUE TITLE
Running hello world example

### ISSUE THREAD

**Issue by abditag2** [linaro-swg/hello_world#13]
I have followed the instructions and was able to compile the project. Then I copied the filed host/hello_world to the my raspberry pi OS and was able to execute it. However, when I change the content of the hello_world_ta.c, it does not seem to affect the results of the execution. 

Do I need to separately copy the trusted application too?

**Comment by jforissier** [comment]
Yes. The TA binary is `<uuid>.ta` and should be copied to `/lib/optee_armtz`.

**Comment by abditag2** [comment]
Thank you! this solved the problem.
