### ISSUE TITLE
hello_world compiled error

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/hello_world#14]
Hi, I followed the steps to comile the hello_world to  64-bit
```bash
    export TEEC_EXPORT=$PWD/../optee_client/out/export
    export HOST_CROSS_COMPILE=$PWD/../toolchains/aarch64/bin/aarch64-linux-gnu-
    export TA_CROSS_COMPILE=$PWD/../toolchains/aarch64/bin/aarch64-linux-gnu-
    export TA_DEV_KIT_DIR=$PWD/../optee_os/out/arm/export-ta_arm64
    make
```
then get erros：
     skipping incompatible /home/optee/hello_world-master/../optee_client/out/export/lib/libteec.so when searching for -lteec
     cannot find -lteec
      collect2: error: ld returned 1 exit status
      Makefile:21: recipe for target 'hello_world' failed

Then I found the file libteec.so.1.0 is in 32-bit, is this the cause? how to solve it ?

**Comment by jforissier** [comment]
Hi @bryan370210,

Please make sure you set `CROSS_COMPILE` to the 64-bit compiler when building `optee_client`. You will need to `make clean` first, to delete the 32-bit library.

**Comment by bryan370210** [comment]
@jforissier ，
it doesn't work, it looks like the file  libteec.so.1.0 is genarated by optee, not hello_world.
I make clean and make again, get the same error, then I rename the file libteec.so.1.0 , make again,
get error: -lteec not found
then restore  libteec.so.1.0,  incompatible again

**Comment by jockebech** [comment]
@bryan370210 , may I suggest that you use hello world in https://github.com/linaro-swg/optee_examples instead of the current one? The one you are working with is the old one, but we moved all this into the optee_examples git, so it resides there with a couple of other examples. I'm 100% sure optee_example is working (I used it yesterday).

I think I'll add a pull request to this particular git which will say that this is obsolete and redirect people to optee_examples instead.

**Comment by jockebech** [comment]
#15 has been created to deprecate/obsolete this particular git.

**Comment by jforissier** [comment]
`libteec.so.1.0` is generated by [`optee_client`](https://github.com/OP-TEE/optee_client/). You did not say how you are building the whole thing so that's all I can say, again make sure `CROSS_COMPILE` is set correctly when you're building `optee_client`.

**Comment by bryan370210** [comment]
@jbech-linaro @jforissier 
 I try to build `https://github.com/linaro-swg/optee`_examples in `linaro-swg/hikey_optee`,
```bash
         export TEEC_EXPORT=out/target/product/hikey/obj/lib
         export HOST_CROSS_COMPILE=toolchains/aarch64/bin/ aarch64-linux-gnu-
         export TA_CROSS_COMPILE=toolchains/aarch64/bin/ aarch64-linux-gnu-
         export TA_DEV_KIT_DIR=optee/optee_os/out/arm-plat-hikey/export-ta_arm64
         make

/data2/optee_android/7.1.2_r33/toolchains/aarch64/bin/aarch64-linux-gnu-gcc -o optee_hello_world main.o -lteec -L/data2/optee_android/7.1.2_r33/out/target/product/hikey/obj/lib
```

and get this error:
```bash
        warning: libc++.so, needed by /data2/optee_android/7.1.2_r33/out/target/product/hikey/obj/lib/libteec.so, not found (try using -rpath or -rpath-link)
/data2/optee_android/7.1.2_r33/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../../../aarch64-linux-gnu/bin/ld: /data2/optee_android/7.1.2_r33/toolchains/aarch64/bin/../aarch64-linux-gnu/libc/usr/lib/crt1.o: undefined reference to symbol '__libc_start_main@@GLIBC_2.17'
/data2/optee_android/7.1.2_r33/toolchains/aarch64/bin/../aarch64-linux-gnu/libc/lib/libc.so.6: error adding symbols: DSO missing from command line
```

**Comment by jockebech** [comment]
Are you using the Android toolchain when trying to build a normal OP-TEE setup or vice versa? Or are you indeed following the build steps as described [here](https://github.com/OP-TEE/build#5-platforms-supported-by-buildgit) (hikey.xml)?

**Comment by bryan370210** [comment]
@jbech-linaro 
 no, I buid the linaro-swg/optee_android_manifest
followed the steps https://github.com/linaro-swg/optee_android_manifest
then I try to build examples, 

I don't find toolchains in linaro-swg/optee_android_manifest

so the toolchain comes from here
https://github.com/OP-TEE/build#5-platforms-supported-by-buildgit

7.4 Get the toolchains
In OP-TEE we're using different toolchains for different targets (depends on ARMv7-A ARMv8-A 64/32bit solutions). In any case start by downloading the toolchains by:
$ cd build
$ make toolchains

then I copyed them into linaro-swg/optee_android_manifest

**Comment by jockebech** [comment]
@vchong, for Android build, you are using Android toolchain to build libteec and host binaries and the non-Android toolchain to build TA's? Right? Also the [Android.mk](https://github.com/linaro-swg/optee_examples/blob/master/Android.mk) in optee_examples include individual Android.mk files, so this should be built as part of the full Android build, right? (It's a long time since I build Android myself).

**Comment by bryan370210** [comment]
@jbech-linaro 
I made a mistake .

I have build the full Android and burn it into the board, and I have wrote a progam,and want to buid it, then push it to the device. so I try it on the examples but failed .  how to do that?

**Comment by vchong** [comment]
@bryan370210 This was explained in https://github.com/OP-TEE/optee_os/issues/1809. https://github.com/OP-TEE/build is for an initramfs-based Linux build. https://github.com/linaro-swg/optee_android_manifest is for an Android build. They're different build system so please don't mix them together. You should integrate your program into the Android build system and get it to build under that environment. Why are you trying to build your program separately instead?

Similar to what's mentioned in https://github.com/OP-TEE/optee_os/issues/1809, you can use `external/optee_examples/hello_world` as a reference for your program. E.g. `cp external/optee_examples/hello_world external/optee_examples/my_program` and make the necessary changes to the relevant files in `external/optee_examples/my_program`.

Or even easier, just put your code in `external/optee_examples/hello_world` and use that as your program. Then you don't need to worry about integrating your program.

@jbech-linaro The android toolchain is used for both. `optee_examples` can be built as part of the full build or by specifying the module as the target, e.g. `make <bla bla options> optee_example_hello_world; make <bla bla options> <uuid>.ta`.

**Comment by bryan370210** [comment]
@vchong 
the time of building the entire Android system is too long, so I want to build the program separately. then push them to the device. can you talk more About that make bla bla options optee_example_hello_world; make bla bla options uuid.ta.

**Comment by vchong** [comment]
@bryan370210 Just run the same make command you used to build Android, but append the target module name at the end. I.e.

`make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true 
CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true 
TARGET_BUILD_UEFI=true optee_example_hello_world`

`make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true 
CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true 
TARGET_BUILD_UEFI=true 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta`

Note that if you use your own program, e.g. `external/optee_examples/my_program`, you also need to update `device/linaro/hikey/optee-packages.mk` as instructed in https://github.com/OP-TEE/optee_os/issues/1809, or else the below commands won't work.

`make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true 
CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true 
TARGET_BUILD_UEFI=true my_program_name`

`make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true 
CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true 
TARGET_BUILD_UEFI=true <my_ta_uuid>.ta`

Perhaps I should avoid using `bla bla` in future responses. ;s

**Comment by bryan370210** [comment]
@vchong 

build/core/base_rules.mk:183: *** device/generic/goldfish-opengl/shared/OpenglCodecCommon: MODULE.TARGET.STATIC_LIBRARIES.libOpenglCodecCommon already defined by data2/generic/goldfish-opengl/shared/OpenglCodecCommon.
build/core/ninja.mk:163: recipe for target 'out/build-aosp_arm.ninja' failed
make: *** [out/build-aosp_arm.ninja] Error 1

**Comment by vchong** [comment]
@bryan370210 This is not a hikey build. Did you run `source ./build/envsetup.sh` and `lunch hikey-userdebug` commands first?

Did you run any commands with `sudo`? If yes, please don't.

**Comment by bryan370210** [comment]
@vchong 
I find the problem, the out directory is created by root. 
thank you

**Comment by vchong** [comment]
@bryan370210 you're welcome. Closing issue now. Please open a new one if necessary.
