### ISSUE TITLE
DMSG is EMSG?

### ISSUE THREAD

**Issue by vchong** [linaro-swg/hello_world#2]
I'm seeing `DMSG` in TA code being prefixed with `ERROR:` instead of `DEBUG:` in secure world logs. Same case for https://github.com/jenswi-linaro/lcu14_optee_hello_world. Any ideas where to look for debugging this? Thanks!

**Comment by vchong** [comment]
```
ERROR:   TEE-CORE: DEBUG:   USER-TA:TA_CloseSessionEntryPoint:92: Goodbye!
ERROR:   TEE-CORE: DEBUG:   USER-TA: tee_user_mem_free:438: Free: link:[0x115058], buf:[0x115068:16]
ERROR:   TEE-CORE: DEBUG:   USER-TA:TA_DestroyEntryPoint:51: has been called
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:355:    ... Destroy TA ctx
```

**Comment by jockebech** [comment]
Seems to be related to [this](https://github.com/jbech-linaro/optee_os/commit/8be7fb9a9cc1407f409f3ed8d8491379a4672634) patch which Phil hacked together for RPi3 (he told me that it works, but it should be done in a less hacky way).

**Comment by vchong** [comment]
Fixed in https://github.com/OP-TEE/optee_os/pull/1124.
